- type: application/vnd.dotmpe.project
  id: bvberkum/munin-server
  env: ENV_NAME=.. . ./env.sh
  scripts:
    build-docker:
      - docker build \
          --build-arg BASE_TAG=xenial \
          -t munin-server:xenial .
    rm-docker:
      - docker rm -f ${hostname}-munin-server
    run-docker:
      - docker run -d -P \
          $add_hostlist \
          --name ${hostname}-munin-server \
          --env-file .env \
          --hostname munin.${domainname} \
          -v $DCKR_VOL/munin/logs:/var/log/munin:rw \
          -v $DCKR_VOL/munin/db:/var/lib/munin:rw \
          -v $DCKR_VOL/munin/run:/var/run/munin:rw \
          -v $DCKR_VOL/munin/cache:/var/cache/munin:rw \
          -v /etc/localtime:/etc/localtime:ro \
          \
          munin-server:xenial

- type: application/vnd.dotmpe.environment
  id: bvberkum/munin-server-main
  main: bvberkum/munin-server
