- type: application/vnd.org.wtwta.project
  id: bvberkum/munin-server
  env: . $HOME/.local/etc/scalingo-munin-server.sh
  scripts:
    init:
      - htd package update
      - htd package remotes-init
      - vc regenerate
    build-docker:
      - docker build \
          --build-arg BASE_TAG=xenial \
          -t munin-server:xenial .
    rm-docker:
      - docker rm -f ${hostname}-munin-server
    run-docker:
      - docker run -d -P \
          $add_hostlist \
          --name ${hostname}-munin-server \
          --env-file $HOME/.local/etc/scalingo-munin-server.env \
          --hostname munin.${domainname} \
          -v $DCKR_VOL/munin/logs:/var/log/munin:rw \
          -v $DCKR_VOL/munin/db:/var/lib/munin:rw \
          -v $DCKR_VOL/munin/run:/var/run/munin:rw \
          -v $DCKR_VOL/munin/cache:/var/cache/munin:rw \
          -v /etc/localtime:/etc/localtime:ro \
          \
          bvberkum/munin-server:xenial
  urls:
    upstream: https://github.com/Scalingo/docker-munin-server
    github: https://github.com/bvberkum/docker-munin-server
    docker: https://hub.docker.com/r/bvberkum/munin-server
    layers: https://microbadger.com/images/bvberkum/munin-server

  repositories:
    origin: git@github.com:bvberkum/docker-munin-server.git
    upstream: git@github.com:Scalingo/docker-munin-server.git

- type: application/vnd.org.wtwta.environment
  id: bvberkum/munin-server-main
  main: bvberkum/munin-server
