#!/bin/sh

# Build script for hub.docker.com

case "$DOCKER_TAG" in

  latest )   BASE_TAG=xenial ;;

  * )        BASE_TAG=latest ;;

esac

docker build \
    --build-arg BASE_TAG=$BASE_TAG \
    -t $IMAGE_NAME .
